version: '3'
services:
  #Database MySql
  db:
    image: mysql:5.7
    container_name: "wordpress_mysql"
    restart: always
    volumes:
       - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - back  
  #WordPress CMS
  wordpress:
    depends_on:
      - db
    image: wordpress-with-java:5.4.1
    container_name: "wordpress"
    restart: always
    volumes:
      - ./wordpress:/var/www/html
      - ./cgi-bin:/usr/lib/cgi-bin  
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      #Java
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/jvm/default-java/bin:/usr/lib/jvm/default-java/db/bin
      JAVA_HOME: /usr/lib/jvm/default-java 
    ports:
      - '8000:80'
    networks:
      - back
networks:
  back:
volumes:
  db_data: